FROM	    debian:trixie-slim
MAINTAINER  Peter Bui <pbui@nd.edu>

ENV	    DEBIAN_FRONTEND="noninteractive"

RUN	    apt install --update -y \
		python3-tornado python3-requests python3-yaml \
		bash \
		gcc g++ \
		python3 \
		ruby \
		default-jdk-headless \
		golang \
		guile-2.2 \
		ghc \
		sbcl \
		mono-complete \
		ocaml \
		nodejs npm \
		rustc && \
	    apt clean && \
	    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
